  version: '2'
services:
    db:
      image: mysql:5.7
      volumes:
       - data_db:/var/lib/mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=12345678
volumes:
  data_db:
